version: "3.8"
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
