name: CI app build

on:
  pull_request:
    branches:
      - "stage"
      - "main"
      - "release/**"
  # push:
  #   branches-ignore:
  #     - "stage"

# this will cancel in progress workflows with the same name and branch if a newer one is started
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run install-modules
      - run: npm run build:server
      - run: npm run build:client
