name: CI app build

on:
  pull_request:
    branches:
      - "stage"
      - "main"
      - "release/**"
  # push:
  #   branches-ignore:
  #     - "stage"

# this will cancel in progress workflows with the same name and branch if a newer one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        id: node_setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - name: Install And Build
        run: npm run install-modules && npm run build:client && npm run build:server
